site_name: Youtube Playlist Analyzer
site_description: A tool to analyze and get insights from YouTube playlists
site_author: Karan Saini
repo_url: https://github.com/805karansaini/youtube_playlist_analyser

theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: deep purple
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: deep purple
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - search.suggest
    - search.highlight
    - content.code.copy    # Changed from code.copy to content.code.copy

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            render_type: markdown
            show_source: true
            show_root_heading: true
  - minify:
      minify_html: true

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - toc:
      permalink: true

nav:
  - Home: index.md
  - Reference:
      - Config: reference/config.md
      - Main: reference/main.md
      - Home Routes: reference/home_routes.md
      - Youtube Service: reference/youtube_service.md
      - Utils: reference/utils.md
      - Exceptions: reference/exceptions.md
